[tool.poetry]
name = "miniheroes"
version = "0.1.0"
description = ""
authors = ["Mohit Narayan Vashisth <mohitnarayanvashisth2703@gmail.com>"]
readme = "README.md"
packages = [{ include = "miniheroes", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.scripts]
miniheroes = "miniheroes.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"